server:
  port: 8888
  tomcat:
    max-http-header-size: 8192

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.238.146.149:3306/jsp?useUnicode=true&characterEncoding=utf-8&useSSL=true&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  # file: /opt/spring_log.log

mybatis:
  type-aliases-package: com.nit.ssm.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
application:
  jwt:
    # 加密秘钥
    secret: ADB8E3D5838A0AE8E274014928CE2CEE
    # token有效时长，60 * 4小时，单位分钟
    expire: 240
    sm4Key: 20250902A4591288621A1DC45DF6ACE3